name: generating a docker image on dockerhub

on:
    workflow_call: 

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0o

    - name: Download a Build Artifact 
      uses: actions/download-artifact@v3.0.0
      with: 
        name: Package

    - name: docker Login 
      uses: docker/login-action@v2.0.0 
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build and push docker images
      uses: docker/build-push-action@v3.0.0
      with: 
        context: .
        file: ./Dockerfile.ci
        push: true 
        tags: ${{ secrets.DOCKER_USERNAME }}/go_ci:latest