name: build-java-application

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: run tests
        run: mvn clean test 

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build project 
        run: mvn --batch-mode --update-snapshots verify

      - name: staging build
        run: mkdir staging && cp target/*.jar staging

      - name: upload a build artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: staging

  docker:
    needs: build 
    uses: ./.github/workflows/docker.yaml
    secrets: inherit
